### ISSUE TITLE
Incompatibility with Sponge

### ISSUE THREAD

**Issue by AngelusQQ** [DimensionalDevelopment/JustEnoughIDs#1]
https://pastebin.com/3eKnrnqk

VanillaFix-1.0.9-95 starts up with no problems.

**Comment by Runemoro** [comment]
Thanks for the report, this will be fixed for version 1.0.1.

**Comment by Bulldog83** [comment]
I have the same crash, but w/o sponge.
https://gist.github.com/Bulldog83/06c617f8c5f495d471462ee3ec31a328

**Comment by Runemoro** [comment]
@Bulldog83 That's not the same crash. It was fixed in the latest dev version. Next curseforge version will be released soon fixing both of these bugs.

**Comment by Bulldog83** [comment]
Ok, thanks.

**Comment by SacrificialFlame** [comment]
How soon will this be fixed as I plan to release a new modpack update today with this mod?

**Comment by ZombieHDGaming** [comment]
As soon as we can. As we aren't sure what exactly is the issue with JEID and Sponge, we are waiting for our resident Sponge guy to get back to us so we can figure out how to fix this.

**Comment by Runemoro** [comment]
We're waiting for a reply from Sponge to see what the problem could be. We'll probably release it in 1-2 days.

**Comment by Runemoro** [comment]
This was fixed in SpongeForge build #3209. 

For the other bug, there will be a new CurseForge release soon, but until then you can use this dev build: https://github.com/DimensionalDevelopment/JustEnoughIDs/releases/tag/untagged-71910026ef2f50a38ab3
