### ISSUE TITLE
Possible compat issues with Repose and Better Foliage

### ISSUE THREAD

**Issue by Sunconure11** [DimensionalDevelopment/JustEnoughIDs#10]
https://paste.dimdev.org/vibuvapome.mccrash

https://paste.dimdev.org/upiroranod.mccrash

**Comment by Runemoro** [comment]
Neither are caused by JEID, report these to Repose and Better Foliage instead.

**Comment by Sunconure11** [comment]
I have done so.

However, I'm requesting this to be reopened, just in case something weird is going on in here or VanillaFix. I ran into one of the crashes this mod is having without JEID.

https://github.com/octarine-noise/BetterFoliage/issues/188

https://github.com/delvr/Repose/issues/29

**Comment by Runemoro** [comment]
It is impossible for this to be caused by JEID, they happened in parts of Minecraft that JEID and VF don't touch.
