### ISSUE TITLE
JEID seems to be incompatible with jdk-8.0.212.04-openj9

### ISSUE THREAD

**Issue by katubug** [DimensionalDevelopment/JustEnoughIDs#105]
After close to two hours of testing, I have finally (I think) managed to troubleshoot what my issue is. Phew. It's been a ride, let me tell ya, haha.

The short version is: I have found that when I assign either Twitch launcher or MultiMC to use the latest openj9, it hangs during the launch process. When I have my full modlist installed, it will load up to forge 2/7, right around when Chisel is listed as loading. When I have only JEID installed, it stops after "Setting User."

latest.log: https://pastebin.com/yFh8TfEb
debug.log: https://pastebin.com/gBQVpAmE

Both logs are from a completely fresh MultiMC instance, with only JEID 1.0.3-48, using Forge 14.23.5.2847 (but I have also tested with 2838 and had the same issue).

I had previously been using an older version of openj9 without issue, but unfortunately as it was removed from my pc I can't get you an exact version.

Please let me know if there's any other information you need!

**Comment by sam-kirby** [comment]
Sounds like #102, try 1.0.3-50 available [here](https://github.com/DimensionalDevelopment/JustEnoughIDs/releases/tag/untagged-5159f1d8e5fb37beaf74) and see if it resolves your issue.

**Comment by katubug** [comment]
Ah, shoot, yanno I even got linked to that issue, but I didn't see anything about java versions, so I thought this might be different.

But, testing 1.0.3-50 in the same environment does fix the hang, so yeah this must be a duplicate. I completely understand if you guys have no ballpark on release of the new version, but if you have a rough estimate it would be rad. No worries either way, though.

Should I close this issue as duplicate?

**Comment by sam-kirby** [comment]
Pester @ZombieHDGaming for a release, I can't do that.

**Comment by katubug** [comment]
Fair! I didn't mean to aim that at you personally, just the team at large. Thanks for pinging them, I appreciate it! But also, it's not a huge issue, I've swapped back to Hotspot for the meantime. I was just wondering.

Thanks again!

**Comment by Mysticpasta1** [comment]
seems fixed
