### ISSUE TITLE
Minecraft Somtimes Won't Start With JEID

### ISSUE THREAD

**Issue by KangyKSLG** [DimensionalDevelopment/JustEnoughIDs#108]
Hi,

Not sure what info to attach to this as I don't get any crashes or messages I recognise but I have the console output for you.

Sometimes when starting minecraft it will hang on the same line and others it will start normally. Seems completely random.

Whatever info you need please let me know and i'll do my best to provide it.
[Minecraft Start Log.txt](https://github.com/DimensionalDevelopment/JustEnoughIDs/files/3952026/Minecraft.Start.Log.txt)

**Comment by sam-kirby** [comment]
Possibly a duplicate of #105 and #102 

Can you try the version referenced by those issues and see if the problem continues?

**Comment by KangyKSLG** [comment]
Sure thing. I'll try now and get back with you asap with the results

**Comment by KangyKSLG** [comment]
Hi, yep that's done the trick! Now starting 10 times out of 10 :) 

Thanks, i'll close the issue
