### ISSUE TITLE
Very weird (and serious) error (ID Limit Exceeded / Failure to patch Forge)

### ISSUE THREAD

**Issue by BrisingrAerowing** [DimensionalDevelopment/JustEnoughIDs#109]
I'm somehow getting the ID limit exceeded error from Forge with JEID installed.

JEID 1.0.3-48

[Crash Log](https://paste.dimdev.org/umimejehib.mccrash)

**Comment by sam-kirby** [comment]
Any chance you could provide a full log?

**Comment by BrisingrAerowing** [comment]
The issue disappeared for one of my packs with over 4096 blocks. I haven't tried any of my other packs yet. The only change I've done is reinstalling MultiMC, though I'm not sure how that would break / unbreak things. I'll do some more testing and report back.

**Comment by BrisingrAerowing** [comment]
I've identified the mod at fault: [LootingVI](https://www.curseforge.com/minecraft/mc-mods/lootingvi). Removing it prevents the crash.
