### ISSUE TITLE
Jeid 1.0.3-48 and Spongeforge 2705-7.1.0

### ISSUE THREAD

**Issue by TheAJArts** [DimensionalDevelopment/JustEnoughIDs#112]
I added JEID to be able to use WorldEdit with Blocks from Enderio and a few other mods. 
When I use //set in WorldEdit (Doesnt matter which block, even Minecraft blocks) it removes all the blocks in the selection and doesnt place anything. Now I tried to remove JEID after this issue and WorldEdit continued to not work.
Now, every time I try and remove JEID, I get a "jeid-biome:error 112" and it deletes most of the biome all the way to the void, having to backup the world and re-add jeid.

WorldEdit: worldedit-sponge-api7.1.0-6.1.10-SNAPSHOT-dist
BOP: BiomesOPlenty-1.12.2-7.0.1.2399-universal

**Comment by TheAJArts** [comment]
After some testing, Minecraft blocks are working but any number above the 4095 limit does not work.

**Comment by ZombieHDGaming** [comment]
The plugin won't work with JEID, you need the official WorldEdit mod for JEID extensions to work.
