### ISSUE TITLE
Incompatible with Mixin 0.8 / Newer sponge versions

### ISSUE THREAD

**Issue by clienthax** [DimensionalDevelopment/JustEnoughIDs#115]
https://github.com/SpongePowered/SpongeForge/issues/3069

**Comment by tankcr** [comment]
Do we have any kind of timeline on a resolution to this issue?

**Comment by clienthax** [comment]
I'm looking into this but there seems to be other issues caused by this too.

**Comment by clienthax** [comment]
https://github.com/DimensionalDevelopment/JustEnoughIDs/pull/117
https://github.com/DimensionalDevelopment/VanillaFix/pull/234
