### ISSUE TITLE
Game crash w/ JEID v1.0.3-5x and Dynamic Surroundings

### ISSUE THREAD

**Issue by Klaasgow** [DimensionalDevelopment/JustEnoughIDs#130]
Minecraft crashes with v55 and 54 when paired with Dynamic Surroundings - **but v1.0.3-48 works fine**. There seems to be a problem with mixin and maybe it's just Dynamic Surroundings that is not up to date, or causing the issue...

Here's the log: https://pastebin.com/U5cEFTsp

**Comment by agentwolf88** [comment]
Same here

https://paste.ee/p/nK93z

**Comment by ZombieHDGaming** [comment]
DynamicSurroundings has updated, and Agentwolf is using an outdated MalisisCore.

**Comment by agentwolf88** [comment]
MalisisCore is not the problem.

https://paste.dimdev.org/iqusujatof.mccrash

**Comment by ZombieHDGaming** [comment]
It *was* one of the issues, update your mods. VanillaFix isn't even at the latest and I doubt Phosphor is either, so this is more user negligence and not keeping mods updated
