### ISSUE TITLE
NoSuchFieldException: processor

### ISSUE THREAD

**Issue by GuyFawkes76** [DimensionalDevelopment/JustEnoughIDs#131]
The error occurs on 2 last versions of JEID (-54 and -55), on the -48 version there is no such error.
Here is the crash report: https://pastebin.com/RQEttytK

**Comment by ZombieHDGaming** [comment]
MalisisCore needs a new release to support Mixins 0.8, which the forked version already does, Dockter just needs to release it, so no issue here besides a mod needing a new release.

**Comment by GuyFawkes76** [comment]
The problem still occurs even without MalisisCore and Doors.

**Comment by ZombieHDGaming** [comment]
Then please upload your full log so I can view it

**Comment by GuyFawkes76** [comment]
Do you mean the debug.log?

**Comment by ZombieHDGaming** [comment]
No, I mean your normal game log

**Comment by GuyFawkes76** [comment]
https://pastebin.com/Swxq3pSH Here it is

**Comment by ZombieHDGaming** [comment]
The issue is ForgeEssentials, which I don't know why they'd need Mixins, but okay.....if you're using that mod to replace Essentials on a server or what not, there's 2 server types: Magma and Mohist that can accomplish this no problem
