### ISSUE TITLE
Since it removes Item ID's (numerical one's), FAWE on 1.12.2 Sponge doesn't work

### ISSUE THREAD

**Issue by LokeYourLord** [DimensionalDevelopment/JustEnoughIDs#139]
Since JEID makes the ID format for 1.12.2 to the one of 1.13+, I cannot use mods like WorldEdit and FastAsyncWorldEdit. If I want to do a //set with FastAsyncWorldEdit in 1.12.2, it requires a numerical ID (I have not been able to get names to work with it), so changing blocks to modded blocks is impossible. Is there a way to remedy this somehow? Thanks~

**Comment by LokeYourLord** [comment]
Found a solution, not a great one but acceptable.

**Comment by GodMorduk** [comment]
@LokeYourLord so what is a solution?

**Comment by SakuraWuhen** [comment]
> 找到了一个解决方案，不是很好，但可以接受。

Hope to be able to tell you the solution, thank you!

**Comment by LokeYourC3PH** [comment]
Well, so the solution for those of you seeking it out, is that you should do the following:
1: Place modded block in front of you
2: Use the "//info" command to bind the Info tool to your hand or whatever item you are currently holding
3: Right click the modded block in front of you to get the block ID of said modded block
4: Use "//none" command to unbind the Info tool from your hand
5: Use the provided block ID in whatever command you need it for (//set, //replace, etc.)

Note: This solution works for _**almost**_ all blocks, but not 100% all, as some blocks act weird or have sub ID's or NBT data that isn't revealed with the //info tool.

**Comment by SakuraWuhen** [comment]
Great, thank you so much!
