### ISSUE TITLE
Not an issue

### ISSUE THREAD

**Issue by TacticalUniverse** [DimensionalDevelopment/JustEnoughIDs#14]
Any idea when the a new update will be out or when things should be fixed

**Comment by ZombieHDGaming** [comment]
Hopefully next week. Rune and I have been kinda busy and haven't had a chance to fix anything lately. We should be getting back into things next week and hopefully have some things fixed by the end of it, if not 2 weeks from now.

**Comment by TacticalUniverse** [comment]
Any news on the fix for this mod as I have people who want to play my pack/server and cant till the bugs/crash to desktop r fixed
