### ISSUE TITLE
Change DataVersion Tag?

### ISSUE THREAD

**Issue by TBlueF** [DimensionalDevelopment/JustEnoughIDs#148]
Hey,

i was looking into making my project [BlueMap](https://github.com/BlueMap-Minecraft) maybe supporting worlds stored using JustEnoughIDs when i noticed that the `DataVersion` tag of the stored chunks is the same as it is with vanilla 1.12 worlds.
With that being the case there is no straight forward method for me to detect the jeid-format from the world-files. (or is there?)

I was wondering if that version-tag should be adapted to signal a different storage-format?

Since the palette-format also differs from the 1.13-palette i think it should even be a version number that is not used with vanilla-minecraft at all. Any thoughts? :)

**Comment by Dreaming-Codes** [comment]
![image](https://user-images.githubusercontent.com/10401566/109993350-7b800880-7d0c-11eb-966b-e5ec2c4d8432.png)

**Comment by TBlueF** [comment]
I don't need this anymore since i am dropping 1.12 support soon anyways..
I was not aware of that version tag, that would probably be sufficient ^^

I think it would probably be good practice to have that version per-chunk, tho .. since each chunk could theoretically have a different version format..

I'll still close this, since there is probably no point in implementing this now at this point :)
