### ISSUE TITLE
A mod doesn't support extended biome IDs

### ISSUE THREAD

**Issue by xJon** [DimensionalDevelopment/JustEnoughIDs#152]
Hi,
I've encountered 2 items in my modpack that show that message:
![Screenshot_2](https://user-images.githubusercontent.com/8945347/90322945-80918c00-df63-11ea-987b-5d0147f843f8.png)
Any idea what is it about? Is there a way to know?
Thank you!

**Comment by EnderBro123** [comment]
Remove Mystcraft and your good.

**Comment by Runemoro** [comment]
See https://github.com/DimensionalDevelopment/JustEnoughIDs/issues/158.
