### ISSUE TITLE
Bungeecore

### ISSUE THREAD

**Issue by NordicGamerFE** [DimensionalDevelopment/JustEnoughIDs#155]
This mod seems to work badly with Bungeecore 
A suggest would be for JEIDS to detect if a server has the mod installed and disable it client side if said server does not have it installed

**Comment by ZombieHDGaming** [comment]
1. That's not how mods work, you can't just detect if a mod exists on a server without having Forge or a way to send packets between the client and server, which even then, is still difficult to tell if it exists.
2. You can't just disable the mod on the fly, again, that's not how it works. We have to modify Minecraft internals before the game can technically launch and it can't be reversed without stopping the game first. There's nothing we can do about that besides say, don't play with a modpack with JEID on a Spigot server cause it's not gonna work.

**Comment by Runemoro** [comment]
It sounds like you're trying to join a vanilla server (behind BungeeCord) with JEID on the client? Or is there actually an issue with joining BungeeCord-linked servers *which have the mod installed*? If not, see https://github.com/DimensionalDevelopment/JustEnoughIDs/issues/70#issuecomment-671663267
