### ISSUE TITLE
Leaving personal pocket after relogging sent me to limbo.

### ISSUE THREAD

**Issue by AzQth** [DimensionalDevelopment/JustEnoughIDs#163]
I'm playing on the MCEternal pack. I just acquired a quartz dimensional door and entered my personal pocket dimension for the first time. I do have the issue of setting on fire every time I leave, but I am aware this is a vanilla bug.

When I logged out and back in whilst inside my personal pocket, attempting to leave sent me to limbo. From what I remember, there was a very brief message saying something along the lines of 'You did not use a rift to enter this pocket'. This also occurs with transformational trapdoors, even if I don't relog.

I would like to update this by saying that it is now doing it regardless of whether I relog in the pocket or not.

Edit 2: so I replaced the door and it stopped the problem, so it seems that having it happen once causes it to happen every time after until the door is replaced.

Edit 3: I tried recreating the bug by relogging inside the personal pocket again, and it did not occur. I still set on fire though =P

**Comment by Mysticpasta1** [comment]
https://github.com/DimensionalDevelopment/DimDoors/issues?q=is%3Aissue
