### ISSUE TITLE
exit code zero with latest 1.12.2 release **catastrophic failure**

### ISSUE THREAD

**Issue by Sulferix** [DimensionalDevelopment/JustEnoughIDs#173]
Mod Version:
JustEnoughIDs 1.0.3-54
JustEnoughIDs 1.0.3-55

Forge Version:
2855

Link to client log:
exit code zero.
Link to crash log:

exit code zero
Description:
the single most annoying possible mod failure is exit code zero. the fact that this mod only has that issue with the last 2 release version 1.12.2 files is beyond infuriating. this mod single handedly prevented me from updating my modpack and gave me one of the biggest headaces ive ever had. a crash with NO CRASH LOG and NO LOG OF ANY KIND. yikes. dont go telling me i didnt provide enough information either. thanks to exit code zero, i dont even get any. i will not test this with deleting all 218 of my mods either. not worth the headace. if someone wants to dig in than go ahead, ill attatch my mod list with this unrelated crash log.

https://paste.dimdev.org/otifewifom.mccrash

there needs to at least be a post with that 1.12 release explaining the possibility of this issue or a removal of that version entirely.

**Comment by MagmaBro123** [comment]
Also having a crash.
[crash-2021-06-21_06.42.35-client.txt](https://github.com/DimensionalDevelopment/JustEnoughIDs/files/6686644/crash-2021-06-21_06.42.35-client.txt)

**Comment by MrRedstoneA1** [comment]
Have you tried using VanillaFix? It tells you which mod is the most likely culprit for the crash and adds more useful info into crash logs. Note that if the game crashes instantly upon starting then vanillafix can't help you.
