### ISSUE TITLE
Crash.

### ISSUE THREAD

**Issue by MagmaBro123** [DimensionalDevelopment/JustEnoughIDs#174]
The single most annoying possible mod failure ever. All versions of this mod crash. A crash with NO CRASH LOG and NO LOG OF ANY KIND. Don't go telling me I didn't provide enough information either since I can't. Blame your mod and blame the launcher. 

I will not test this with deleting mods since I already tried with just this (Read the crash report if you won't believe me), not worth the headache.

I either get the Exit Code 0 thing, or this crash. Which has a bunch of random numbers all over it and some unreadable Java stuff or whatever that I can't read.

[crash-2021-06-21_06.42.35-client.txt](https://github.com/DimensionalDevelopment/JustEnoughIDs/files/6686636/crash-2021-06-21_06.42.35-client.txt)

Remove this mod and everything related to it if you won't do anything.

**Comment by maxsize213** [comment]
Pretty sure there was already an issue with Better Foliage mentioned in another issue about NEID compatibilty.

**Comment by MagmaBro123** [comment]
Read the crash report...

**Comment by xemnes** [comment]
> 
> 
> Read the crash report...

did you read the crash report? it clearly says you have better foliage installed. and the crash report directly refers to better foliage in that report.
