### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by TacticalUniverse** [DimensionalDevelopment/JustEnoughIDs#18]
I know I asked this last week but is there any update on when we will have a fix for all the crashes as I cant finish my modpack without for our network?

**Comment by ZombieHDGaming** [comment]
I'd suggest for the moment to just use NEID and add JEID once we release the next update. While it's not ideal by any means, I have been busy with work outside of coding and haven't had much of a chance to work on stuff, and Rune has also been busy and working on finishing the next update for VanillaFix. Once Rune finishes that within a few days, JEID will start getting full attention to get things fixed and released. Rune has said he already has some fixes done, but we still have a few other mods to support before it's even remotely ready.

Sorry for the bit of bad news, we've just been busy is all. It'll get fixed (and hopefully released) most likely by the end of next week. Sorry for the long wait.

**Comment by Runemoro** [comment]
Tomorrow.
