### ISSUE TITLE
Removing the mod corrupts worlds.

### ISSUE THREAD

**Issue by MrRedstoneA1** [DimensionalDevelopment/JustEnoughIDs#180]
I removed the mod because it doesn't work with MCEdit. It corrupted all of my worlds. That should be expected but a warning would have been nice. Luckily I keep copies of my worlds.

**Comment by ACGaming** [comment]
It says so on the mod page:
> Extremely important: Removing JustEnoughIDs will break your world. It is equivalent to loading a 1.13 world in 1.12!

**Comment by maxsize213** [comment]
Like what @ACGaming said, it's kind of expected because like NotEnoughIDs, removing it will break your worlds because it's trying to load 1.13 stuff in 1.12 (or if you forked it, below that).

**Comment by throaway123869** [comment]
Should this issue be closed then?

**Comment by MrRedstoneA1** [comment]
Yes, I'll close the issue.
