### ISSUE TITLE
java.lang.RuntimeException: java.lang.NoSuchFieldException: processor

### ISSUE THREAD

**Issue by jtschlierf** [DimensionalDevelopment/JustEnoughIDs#183]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  IELoadingPlugin (ImmersiveEngineering-core-0.12-98.jar)
  CoreMod (betterbiomeblend-1.12.2-1.1.6-forge.jar)
  ForgelinPlugin (Forgelin-1.8.4.jar)
  MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
  OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.2.jar)
  TransformLoader (DynamicSurroundings-1.12.2-3.6.0.2.jar)
  Quark Plugin (Quark-r1.6-179.jar)
  AppleCore (AppleCore-mc1.12.2-3.4.0.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3.jar)
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  TheBetweenlandsLoadingPlugin (TheBetweenlands-3.7.3-SNAPSHOT-20210322.042210-core.jar)
  AstralCore (astralsorcery-1.12.2-1.10.27.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.76-core.jar)
  JustEnoughIDs Extension Plugin (JustEnoughIDs-1.0.3-55.jar)
  CoreMod (Aroma1997Core-1.12.2-2.0.0.2.jar)
Contact their authors BEFORE contacting forge

// Hey, that tickles! Hehehe!

Time: 9/28/21 7:31 PM
Description: Exception in server tick loop

java.lang.RuntimeException: java.lang.NoSuchFieldException: processor
	at net.minecraftforge.fml.common.Loader.handler$beforeConstructingMods$zza000(Loader.java:1150)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:594)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoSuchFieldException: processor
	at java.lang.Class.getDeclaredField(Unknown Source)
	at net.minecraftforge.fml.common.Loader.handler$beforeConstructingMods$zza000(Loader.java:1138)
	... 6 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_301, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1669909744 bytes (1592 MB) / 2774007808 bytes (2645 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 2 total; -Xmx4G -Xms2G
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2855 115 mods loaded, 115 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                                | Version                  | Source                                             | Signature                                |
	|:----- |:--------------------------------- |:------------------------ |:-------------------------------------------------- |:---------------------------------------- |
	| L     | minecraft                         | 1.12.2                   | minecraft.jar                                      | None                                     |
	| L     | mcp                               | 9.42                     | minecraft.jar                                      | None                                     |
	| L     | FML                               | 8.0.99.99                | forge-1.12.2-14.23.5.2855.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| L     | forge                             | 14.23.5.2855             | forge-1.12.2-14.23.5.2855.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| L     | openmodscore                      | 0.12.2                   | minecraft.jar                                      | None                                     |
	| L     | crafttweaker                      | 4.1.20                   | CraftTweaker2-1.12-4.1.20.660.jar                  | None                                     |
	| L     | jei                               | 4.16.1.301               | jei_1.12.2-4.16.1.301.jar                          | None                                     |
	| L     | abyssalcraft                      | 1.10.4                   | AbyssalCraft-1.12.2-1.10.4.jar                     | None                                     |
	| L     | mysticalworld                     | 1.12.2-1.11.0            | mysticalworld-1.12.2-1.11.0.jar                    | None                                     |
	| L     | chisel                            | MC1.12.2-1.0.2.45        | Chisel-MC1.12.2-1.0.2.45.jar                       | None                                     |
	| L     | baubles                           | 1.5.2                    | Baubles-1.12-1.5.2.jar                             | None                                     |
	| L     | endercore                         | 1.12.2-0.5.76            | EnderCore-1.12.2-0.5.76.jar                        | None                                     |
	| L     | tombstone                         | 4.4.7                    | tombstone-1.12.2-4.4.7.jar                         | None                                     |
	| L     | enderio                           | 5.3.70                   | EnderIO-1.12.2-5.3.70.jar                          | None                                     |
	| L     | enderiointegrationtic             | 5.3.70                   | EnderIO-1.12.2-5.3.70.jar                          | None                                     |
	| L     | mantle                            | 1.12-1.3.3.55            | Mantle-1.12-1.3.3.55.jar                           | None                                     |
	| L     | quark                             | r1.6-179                 | Quark-r1.6-179.jar                                 | None                                     |
	| L     | twilightforest                    | 3.11.1021                | twilightforest-1.12.2-3.11.1021-universal.jar      | None                                     |
	| L     | tconstruct                        | 1.12.2-2.13.0.183        | TConstruct-1.12.2-2.13.0.183.jar                   | None                                     |
	| L     | acintegration                     | 1.11.3                   | AbyssalCraft Integration-1.12.2-1.11.3.jar         | None                                     |
	| L     | applecore                         | 3.4.0                    | AppleCore-mc1.12.2-3.4.0.jar                       | None                                     |
	| L     | appleskin                         | 1.0.14                   | AppleSkin-mc1.12-1.0.14.jar                        | None                                     |
	| L     | appliedenergistics2               | rv6-stable-7             | appliedenergistics2-rv6-stable-7.jar               | None                                     |
	| L     | aroma1997core                     | 2.0.0.2                  | Aroma1997Core-1.12.2-2.0.0.2.jar                   | None                                     |
	| L     | aroma1997sdimension               | 2.0.0.2                  | Aroma1997s-Dimensional-World-1.12.2-2.0.0.2.jar    | None                                     |
	| L     | artifacts                         | 1.12.2-1.2.3             | Artifacts-1.12.2-1.2.3.jar                         | None                                     |
	| L     | astralsorcery                     | 1.10.27                  | astralsorcery-1.12.2-1.10.27.jar                   | None                                     |
	| L     | autoreglib                        | 1.3-32                   | AutoRegLib-1.3-32.jar                              | None                                     |
	| L     | betterbedrockgen                  | 6.0.2                    | BetterBedrockGenerator-1.12-6.1.1.jar              | None                                     |
	| L     | bibliocraft                       | 2.4.5                    | BiblioCraft[v2.4.5][MC1.12.2].jar                  | None                                     |
	| L     | guideapi                          | 1.12-2.1.8-63            | Guide-API-1.12-2.1.8-63.jar                        | None                                     |
	| L     | bloodmagic                        | 1.12.2-2.4.3-105         | BloodMagic-1.12.2-2.4.3-105.jar                    | None                                     |
	| L     | bloodmoon                         | 1.5.3                    | Bloodmoon-MC1.12.2-1.5.3.jar                       | None                                     |
	| L     | bonsaitrees                       | 1.1.4                    | bonsaitrees-1.1.4-b170.jar                         | None                                     |
	| L     | botania                           | r1.10-364                | Botania r1.10-364.4.jar                            | None                                     |
	| L     | codechickenlib                    | 3.2.3.358                | CodeChickenLib-1.12.2-3.2.3.358-universal.jar      | None                                     |
	| L     | redstoneflux                      | 2.1.1                    | RedstoneFlux-1.12-2.1.1.1-universal.jar            | None                                     |
	| L     | brandonscore                      | 2.4.20                   | BrandonsCore-1.12.2-2.4.20.162-universal.jar       | None                                     |
	| L     | chameleon                         | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                           | None                                     |
	| L     | comforts                          | 1.4.1.3                  | comforts-1.12.2-1.4.1.3.jar                        | None                                     |
	| L     | conarm                            | 1.2.5.10                 | conarm-1.12.2-1.2.5.10.jar                         | None                                     |
	| L     | cosmeticarmorreworked             | 1.12.2-v5a               | CosmeticArmorReworked-1.12.2-v5a.jar               | None                                     |
	| L     | crafttweakerjei                   | 2.0.3                    | CraftTweaker2-1.12-4.1.20.660.jar                  | None                                     |
	| L     | cucumber                          | 1.1.3                    | Cucumber-1.12.2-1.1.3.jar                          | None                                     |
	| L     | draconicevolution                 | 2.3.28                   | Draconic-Evolution-1.12.2-2.3.28.354-universal.jar | None                                     |
	| L     | draconicadditions                 | 1.16.4                   | Draconic-Additions-1.12.2-1.16.4.44-universal.jar  | None                                     |
	| L     | orelib                            | 3.6.0.1                  | OreLib-1.12.2-3.6.0.1.jar                          | None                                     |
	| L     | dsurround                         | 3.6.0.2                  | DynamicSurroundings-1.12.2-3.6.0.2.jar             | None                                     |
	| L     | enderiobase                       | 5.3.70                   | EnderIO-1.12.2-5.3.70.jar                          | None                                     |
	| L     | enderioconduits                   | 5.3.70                   | EnderIO-1.12.2-5.3.70.jar                          | None                                     |
	| L     | enderioconduitsappliedenergistics | 5.3.70                   | EnderIO-1.12.2-5.3.70.jar                          | None                                     |
	| L     | enderioconduitsopencomputers      | 5.3.70                   | EnderIO-1.12.2-5.3.70.jar                          | None                                     |
	| L     | enderioconduitsrefinedstorage     | 5.3.70                   | EnderIO-1.12.2-5.3.70.jar                          | None                                     |
	| L     | forestry                          | 5.8.2.387                | forestry_1.12.2-5.8.2.387.jar                      | None                                     |
	| L     | enderiointegrationforestry        | 5.3.70                   | EnderIO-1.12.2-5.3.70.jar                          | None                                     |
	| L     | enderiointegrationticlate         | 5.3.70                   | EnderIO-1.12.2-5.3.70.jar                          | None                                     |
	| L     | enderioinvpanel                   | 5.3.70                   | EnderIO-1.12.2-5.3.70.jar                          | None                                     |
	| L     | enderiomachines                   | 5.3.70                   | EnderIO-1.12.2-5.3.70.jar                          | None                                     |
	| L     | enderiopowertools                 | 5.3.70                   | EnderIO-1.12.2-5.3.70.jar                          | None                                     |
	| L     | enderstorage                      | 2.4.6.137                | EnderStorage-1.12.2-2.4.6.137-universal.jar        | None                                     |
	| L     | valkyrielib                       | 1.12.2-2.0.20.1          | valkyrielib-1.12.2-2.0.20.1.jar                    | None                                     |
	| L     | environmentaltech                 | 1.12.2-2.0.20.1          | environmentaltech-1.12.2-2.0.20.1.jar              | None                                     |
	| L     | extrautils2                       | 1.0                      | extrautils2-1.12-1.9.9.jar                         | None                                     |
	| L     | zerocore                          | 1.12.2-0.1.2.9           | zerocore-1.12.2-0.1.2.9.jar                        | None                                     |
	| L     | bigreactors                       | 1.12.2-0.4.5.68          | ExtremeReactors-1.12.2-0.4.5.68.jar                | None                                     |
	| L     | fastleafdecay                     | v14                      | FastLeafDecay-v14.jar                              | None                                     |
	| L     | flansmod                          | 5.10.0                   | Flan's Mod-1.12.2-5.10.0.jar                       | None                                     |
	| L     | fluxnetworks                      | 4.1.0                    | FluxNetworks-1.12.2-4.1.1.34.jar                   | None                                     |
	| L     | forgelin                          | 1.8.4                    | Forgelin-1.8.4.jar                                 | None                                     |
	| L     | icbmclassic                       | 1.12.2-4.0.1.75          | ICBM-classic-1.12.2-4.0.1b75.jar                   | None                                     |
	| L     | ichunutil                         | 7.2.2                    | iChunUtil-1.12.2-7.2.2.jar                         | None                                     |
	| L     | theoneprobe                       | 1.4.28                   | theoneprobe-1.12-1.4.28.jar                        | None                                     |
	| L     | immersiveengineering              | 0.12-98                  | ImmersiveEngineering-0.12-98.jar                   | None                                     |
	| L     | immersivepetroleum                | 1.1.10                   | immersivepetroleum-1.12.2-1.1.10.jar               | None                                     |
	| L     | mekanism                          | 1.12.2-9.8.3.390         | Mekanism-1.12.2-9.8.3.390.jar                      | None                                     |
	| L     | teslacorelib                      | 1.0.18                   | tesla-core-lib-1.12.2-1.0.18.jar                   | None                                     |
	| L     | industrialforegoing               | 1.12.2-1.12.2            | industrialforegoing-1.12.2-1.12.13-237.jar         | None                                     |
	| L     | inventorysorter                   | 1.13.3+57                | inventorysorter-1.12.2-1.13.3+57.jar               | None                                     |
	| L     | ironbackpacks                     | 1.12.2-3.0.8-12          | IronBackpacks-1.12.2-3.0.8-12.jar                  | None                                     |
	| L     | ironchest                         | 1.12.2-7.0.67.844        | ironchest-1.12.2-7.0.72.847.jar                    | None                                     |
	| L     | ironjetpacks                      | 1.1.0                    | IronJetpacks-1.12-2-1.1.0.jar                      | None                                     |
	| L     | journeymap                        | 1.12.2-5.7.1             | journeymap-1.12.2-5.7.1.jar                        | None                                     |
	| L     | jeid                              | 1.0.3-55                 | JustEnoughIDs-1.0.3-55.jar                         | None                                     |
	| L     | mcjtylib_ng                       | 3.5.4                    | mcjtylib-1.12-3.5.4.jar                            | None                                     |
	| L     | mekanismgenerators                | 1.12.2-9.8.3.390         | MekanismGenerators-1.12.2-9.8.3.390.jar            | None                                     |
	| L     | mekanismtools                     | 1.12.2-9.8.3.390         | MekanismTools-1.12.2-9.8.3.390.jar                 | None                                     |
	| L     | nuclearcraft                      | 2.18z                    | NuclearCraft-2.18z-1.12.2.jar                      | None                                     |
	| L     | mekores                           | 2.0.13                   | mekores-2.0.13.jar                                 | None                                     |
	| L     | modernweaponspack                 | 5.14.1                   | Modern Warfare-Content Pack-1.12.2-5.14.1.jar      | None                                     |
	| L     | llibrary                          | 1.7.20                   | llibrary-1.7.20-1.12.2.jar                         | None                                     |
	| L     | mowziesmobs                       | 1.5.8                    | mowziesmobs-1.5.8.jar                              | None                                     |
	| L     | mysticalagriculture               | 1.7.5                    | MysticalAgriculture-1.12.2-1.7.5.jar               | None                                     |
	| L     | mysticalagradditions              | 1.3.2                    | MysticalAgradditions-1.12.2-1.3.2.jar              | None                                     |
	| L     | examplemod                        | 1.0                      | NuclearCraft-2.18z-1.12.2.jar                      | None                                     |
	| L     | openmods                          | 0.12.2                   | OpenModsLib-1.12.2-0.12.2.jar                      | None                                     |
	| L     | openblocks                        | 1.8.1                    | OpenBlocks-1.12.2-1.8.1.jar                        | None                                     |
	| L     | harvestcraft                      | 1.12.2zb                 | Pam's HarvestCraft 1.12.2zg.jar                    | None                                     |
	| L     | patchouli                         | 1.0-23.6                 | Patchouli-1.0-23.6.jar                             | None                                     |
	| L     | projectintelligence               | 1.0.9                    | ProjectIntelligence-1.12.2-1.0.9.28-universal.jar  | None                                     |
	| L     | quarkoddities                     | 1                        | QuarkOddities-1.12.2.jar                           | None                                     |
	| L     | rftools                           | 7.73                     | rftools-1.12-7.73.jar                              | None                                     |
	| L     | simplepartspack                   | 5.14.0                   | Simple Parts-Content Pack-1.12.2-5.14.0.jar        | None                                     |
	| L     | storagedrawers                    | 5.2.2                    | StorageDrawers-1.12.2-5.4.2.jar                    | None                                     |
	| L     | sync                              | 7.1.0                    | Sync-1.12.2-7.1.0.jar                              | None                                     |
	| L     | tetra                             | 0.39.1                   | tetra-1.12.2-0.39.1.jar                            | None                                     |
	| L     | tcomplement                       | 1.12.2-0.4.3             | TinkersComplement-1.12.2-0.4.3.jar                 | None                                     |
	| L     | tinkersjei                        | 1.2                      | tinkersjei-1.2.jar                                 | None                                     |
	| L     | tinkertoolleveling                | 1.12.2-1.1.0.DEV.b23e769 | TinkerToolLeveling-1.12.2-1.1.0.jar                | None                                     |
	| L     | torchslabmod                      | v1.5.2                   | torchslabmod-1.12.2-v1.5.2.jar                     | None                                     |
	| L     | universalmodifiers                | 1.12.2-1.0.16.1          | valkyrielib-1.12.2-2.0.20.1.jar                    | None                                     |
	| L     | waystones                         | 4.1.0                    | Waystones_1.12.2-4.1.0.jar                         | None                                     |
	| L     | ww2pack                           | 5.14.1                   | WW2-Content Pack-1.12.2-5.14.1.jar                 | None                                     |
	| L     | thebetweenlands                   | 3.7.3                    | TheBetweenlands-3.7.3-universal.jar                | None                                     |
	| L     | mysticallib                       | 1.12.2-1.12.0            | mysticallib-1.12.2-1.12.0.jar                      | None                                     |
	| L     | teslacorelib_registries           | 1.0.18                   | tesla-core-lib-1.12.2-1.0.18.jar                   | None                                     |

	Loaded coremods (and transformers): 
IELoadingPlugin (ImmersiveEngineering-core-0.12-98.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
CoreMod (betterbiomeblend-1.12.2-1.1.6-forge.jar)
  
ForgelinPlugin (Forgelin-1.8.4.jar)
  
MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
  mekanism.coremod.KeybindingMigrationHelper
OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.2.jar)
  openmods.core.OpenModsClassTransformer
TransformLoader (DynamicSurroundings-1.12.2-3.6.0.2.jar)
  
Quark Plugin (Quark-r1.6-179.jar)
  vazkii.quark.base.asm.ClassTransformer
AppleCore (AppleCore-mc1.12.2-3.4.0.jar)
  squeek.applecore.asm.TransformerModuleHandler
CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  team.chisel.ctm.client.asm.CTMTransformer
LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3.jar)
  lumien.bloodmoon.asm.ClassTransformer
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
TheBetweenlandsLoadingPlugin (TheBetweenlands-3.7.3-SNAPSHOT-20210322.042210-core.jar)
  thebetweenlands.core.TheBetweenlandsClassTransformer
AstralCore (astralsorcery-1.12.2-1.10.27.jar)
  
EnderCorePlugin (EnderCore-1.12.2-0.5.76-core.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
  com.enderio.core.common.transform.SimpleMixinPatcher
JustEnoughIDs Extension Plugin (JustEnoughIDs-1.0.3-55.jar)
  org.dimdev.jeid.JEIDTransformer
CoreMod (Aroma1997Core-1.12.2-2.0.0.2.jar)
  
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by Mysticpasta1** [comment]
please update to latest JEID with MixinBootstrap
