### ISSUE TITLE
mixin issue on any post 0.8 version without any sponge stuff

### ISSUE THREAD

**Issue by modderchris** [DimensionalDevelopment/JustEnoughIDs#184]
I keep getting this issue where I get an error like this
java.lang.IllegalAccessError: tried to access class org.spongepowered.asm.mixin.transformer.MixinTransformer from class net.minecraftforge.fml.common.Loader
yet this is the CLIENT and no sponge files exist only standard forge and I even tried older and newer than reccomended and deleted "lost cities" to attempt to fix it
yet this error exists depite NO CONFLICTING FILES on any version using mixin 0.8

**Comment by BoogieMonster1O1** [comment]
try installing https://www.curseforge.com/minecraft/mc-mods/mixin-0-7-0-8-compatibility

**Comment by modderchris** [comment]
huh thanks I will try it soon

**Comment by modderchris** [comment]
hmm still fail but I haven't determined if the issue is the same or not

**Comment by Mysticpasta1** [comment]
I'm getting the same issue with one of my modpacks

**Comment by Mysticpasta1** [comment]
Can you find me two post 0.8 mixin mods so I can see about getting the bug fixed

**Comment by Mysticpasta1** [comment]
I'm the current maintainer of the mod

**Comment by Mysticpasta1** [comment]
can I see your list of mods pls modderchris

**Comment by Mysticpasta1** [comment]
modderchris contact me on discord at Hauntedpasta1#8200

**Comment by Mysticpasta1** [comment]
modderchris are you there still

**Comment by Mysticpasta1** [comment]
ModderChris if you are there I need your mod list or two of the offending mods.

**Comment by Mysticpasta1** [comment]
It is mixin bootstrap causing a crash with JEID

**Comment by modderchris** [comment]
I will send you a drive link that includes my current pack attempt

**Comment by modderchris** [comment]
it still happens when I remove jeid and enough mods that it is under 4096
ids

**Comment by modderchris** [comment]
discord guy your tag is invalid

**Comment by BrisingrAerowing** [comment]
This is because the MixinProcessor class was made package-private in Mixin 0.8.3, and JEID tries to access it. You'll need to use reflection to get to it now.

Ref: https://github.com/LXGaming/MixinBootstrap/issues/48#issuecomment-904653743

**Comment by Mysticpasta1** [comment]
How do I do reflection to get it

**Comment by modderchris** [comment]
I am not a coder the coder of jeid needs to add the reflection part

**Comment by Mysticpasta1** [comment]
I am the coder

**Comment by modderchris** [comment]
ok so how do you do reflection? I have no idea how to fix this reference
issue on my own
