### ISSUE TITLE
Incompatible With Biomes'o'Plenty

### ISSUE THREAD

**Issue by ddelaparte** [DimensionalDevelopment/JustEnoughIDs#2]
Receiving the following crash with BoP installed. Since it's one of the most commonly used biome mods (And mod in general) you'll likely want to support it.

https://paste.dimdev.org/qikogaxuwe.mccrash

**Comment by ZombieHDGaming** [comment]
I guess the issue was solved then?

**Comment by Runemoro** [comment]
Biomes O' Plenty is supported and it's what we tested the mod with.
