### ISSUE TITLE
[1.12.2] Incompatibilitie with FoamFix?

### ISSUE THREAD

**Issue by TheSnowyChickens** [DimensionalDevelopment/JustEnoughIDs#20]
Hello,
I have a question.

Someone  told me, your mod is not compatible with FoamFix, is that right?

**Comment by ZombieHDGaming** [comment]
I don't think that's right. We haven't had anyone complain about it not being compatible with the latest release, so I'm pretty positive that FoamFix does work with JEID. You can test it if you so choose to find out.

**Comment by Runemoro** [comment]
It is compatible.

**Comment by TheSnowyChickens** [comment]
Great to hear it.
Thx.
