### ISSUE TITLE
Crash but not sure if its related to JustEnoughIDS

### ISSUE THREAD

**Issue by TacticalUniverse** [DimensionalDevelopment/JustEnoughIDs#21]
https://gist.github.com/TacticalUniverse/f1239dfe52225f84060ae9e8782406bd

This is happening on the server side and no one can figure out what's causing but I figure since Its dealing with Chunks that it would be Just Enough Ids

**Comment by ben-mkiv** [comment]
another one => https://pastebin.com/Pw1eyt83

tried with and without sponge

**Comment by Runemoro** [comment]
This has been fixed thanks to @Aaron1011 . A new version fixing it will be released on CurseForge soon.

**Comment by TacticalUniverse** [comment]
Thank you so much for the fast fix
