### ISSUE TITLE
Will be world migrated using this work fine with minecraft 1.13?

### ISSUE THREAD

**Issue by XakepSDK** [DimensionalDevelopment/JustEnoughIDs#24]
Will be world migrated using this work fine with minecraft + forge 1.13?

**Comment by Runemoro** [comment]
Yes, I will be writing code to upgrade the world to 1.13 when Forge for 1.13 comes out.

**Comment by Robijnvogel** [comment]
I think he was talking about _Vanilla_ Minecraft 1.13.

**Comment by Runemoro** [comment]
No, he asked about "minecraft + forge 1.13". Also, the only way a JEID world would be convertible to a vanilla 1.13 world would be if he had no mods that add blocks/items, and in that case why would he be using 1.13? But in any case, the conversion tool will be able to upgrade a JEID world with no mods to a vanilla world too.
