### ISSUE TITLE
Does not work with world Edit

### ISSUE THREAD

**Issue by TacticalUniverse** [DimensionalDevelopment/JustEnoughIDs#3]
With this mod in a server worldedit does not work with error Java.lang.IllegalArgumentException: can't have a block ID above 4095 (4483 Given) and I figured to post it here as there is no way to get ahold of the world edit dev

**Comment by ZombieHDGaming** [comment]
Are you using the mod or the plugin or.......? We need to know this to check. Also, if you're using mods, WorldEdit should tell you to use the block ID and meta, not the numerical ID in any command.

**Comment by MasterSloth1** [comment]
we tried using //cut and that would spam the console its also the forge mod variant

**Comment by Runemoro** [comment]
Thanks for the report, WorldEdit's check that block IDs are <4096 needs to be disabled.
