### ISSUE TITLE
Render Failure in Dynmap Forge

### ISSUE THREAD

**Issue by SalmonSays** [DimensionalDevelopment/JustEnoughIDs#30]
I'm uncertain if this is a fault of JustEnoughIDs or Dynmap, but launching them alongside each other results in a soft crash/console spam when running a map render. NotEnoughIDs doesn't cause this same crash, but I'd rather not switch back to it if I can avoid it on account of removing mods on occasion from saves.

**Comment by ZombieHDGaming** [comment]
What exactly is the crash? Can you provide your log?

**Comment by SalmonSays** [comment]
For sure, gimme a moment to scrape the relevant bits. It's a soft crash in the sense that the server keeps running but Dynmap stops dead in its tracks, and I'm extremely confident that it's a result of Dynmap and JustEnoughIDs interacting specifically.

**Comment by SalmonSays** [comment]
https://pastebin.com/raw/KDDA29iW

Here's the relevant bit from the server console right after starting a render, though I know it's not much to go on. It happens when JustEnoughIDs and Dynmap are installed on a clean forge server *and* a render is started- removing JEIDs fixes the issue. If you need any more complete logs give me a heads up.

If it's a Dynmap issue I'm happy to pass it along to them, though I'm hopeful it's not a complicated problem.

**Comment by ZombieHDGaming** [comment]
Presumably, they are doing something that requires changes for it to work with JEID. Since they don't have the source for then Forge version available (Which I would yell at them for either way), I'll have to investigate this later and see what they are doing and what changes will need to be made.

**Comment by SalmonSays** [comment]
So is it worth reporting to them alongside any investigation you're personally handling?

**Comment by ZombieHDGaming** [comment]
Yes, I would say it would be worth it since NotEnoughIDs is also having issues as well.

**Comment by SalmonSays** [comment]
I've been running NEID's alongside Dynmap Forge for a while without problems on 1.12.2, is there a specific version you're referring to?

**Comment by ZombieHDGaming** [comment]
No, according to the Dynmap issue tracker, people are having issues with Dynmap and NEIDs, and now apparently JEIDs as well. Whether its something up with the versions, I do not know, but it seems like extended IDs are having issues (which looks to be unrelated to this), alongside our Biome extension feature (which seems like the issue), which will need supported either from our end or their end.

**Comment by SalmonSays** [comment]
Just for reference, Forge 14.23.4.2749 Universal coupled with the latest Dynmap Forge 3.0 alpha-3 and the latest NotEnoughIDs 1.5.4.2 appears to render/work just fine as far as I can tell, in that it actually renders the map and doesn't produce a soft-crash the same way JEID's does with the same version of Dynmap.
