### ISSUE TITLE
Compat Questions

### ISSUE THREAD

**Issue by jredfox** [DimensionalDevelopment/JustEnoughIDs#31]
Do you replace any methods in:
AnvilChunkLoader
Chunk(constructor)
Or any methods at all. I want to be compatible I have line asm injections into everything forge caps do. I have my own cap system that's a bit easy to use and has an onTick() option

**Comment by Runemoro** [comment]
No methods are replaced, it's all just injections.

**Comment by jredfox** [comment]
ok thanks
