### ISSUE TITLE
Debug log spam by unregistered object

### ISSUE THREAD

**Issue by danikk14g** [DimensionalDevelopment/JustEnoughIDs#35]
Hello, i opened the debug file once i loaded a test world for my pack, but the file was being written new lines indefinitely, i closed the world and then i saw 53k lines with the same message:

`[main/DEBUG] [FML]: Attempted to find the oreIDs for an unregistered object (1xitem.lantern@0). This won't work very well.`

i have really no idea what might be causing this.

Thanks in advance.

**Versions**
JustEnoughIDs-1.0.2-16
Forge Mod Loader version 14.23.4.2756 for Minecraft 1.12.2

**Comment by Robijnvogel** [comment]
So what mod adds this "lantern"?

Seems like it's trying to look up if an ItemStack is in an oredictionary while only Items (as in, the type of the ItemStack) can be in an oredictionary.

**Comment by danikk14g** [comment]
sorry for the delay, i was pretty busy today irl, it took my nearly 2 hours to find the mod causing it, AdventurePack, which has a lantern i disabled in the config.

Thanks for the help.
