### ISSUE TITLE
Incompatibility with Lost Cities

### ISSUE THREAD

**Issue by Bulldog83** [DimensionalDevelopment/JustEnoughIDs#4]
Minecraft 1.12.2
Forge Server 14.23.4.2705
JEID 1.0.0-7

This is the world that generated with this version of the mod:
![2018-06-20_21 19 14](https://user-images.githubusercontent.com/20737750/41677505-28589456-74d1-11e8-9716-4c60535aa944.png)
After I disabled it, the world was generated normally.

**Comment by Runemoro** [comment]
Could you give us a list of mods you were using? What biome is that supposed to be, and from what mod is it?

**Comment by Bulldog83** [comment]
This isn't one biome, it's the generation of the whole world.
I'm use: Biomes'o'Plenty, Thaumcraft, Defiled Lands, Abyssal Craft, BuildCraft, Nuclear Craft. It's all the mods that add custom biomes.

**Comment by Bulldog83** [comment]
Did you test the mod with another mods, which uses custom world generation? Such as Biomes o Plenty or OTG?

**Comment by Runemoro** [comment]
Yes, BoP and OTG work. The problem here is Lost Cities.

**Comment by DWX12** [comment]
I can confirm this bug. I am getting the same exact thing when using Lost Cities in addition to this mod. Actually, I one of two things happen, if it happens to load, I get the chunky bedrock world as above or I get a crash saying that it can't find a valid spawn point:

https://paste.dimdev.org/unayumabaw.mccrash

**Comment by Yamza** [comment]
Still an issue.
Modlist: https://i.imgur.com/Vtud824.png

**Comment by mattrix444** [comment]
i can comfirm im getting the same worldgen issue, i tried setting it to where the whole world is a city and i just got bedrock, im not using jeid so not sure if thats the problem, im using void island control mod but no other world gen changing mods

**Comment by SaucissePuree** [comment]
Same here...with Lost Cities Worldgen, it only generates bedrock

**Comment by ubergeek77** [comment]
I'm still having this issue with the latest version of both mods (LostCities 1.12-2.0.12 and JustEnoughIDs 1.0.2-16).

Which mod would have to be fixed for this? Is it a LostCities problem or a JEID problem?

**Comment by DemonfangArun** [comment]
Just ran into this with LostCities 1.12-2.0.12 and JEID 1.0.2-26. Got an internal server crash and locked up client, with a reference to a bird noise causing it after I killed the game (likely irrelevant).

No crash log was generated unfortunately.

**Comment by ZombieHDGaming** [comment]
This issue seems to have been fixed on Lost Cities side (not sure if it has been or not). I'll be closing this issue, but if it's not yet solved, let me know and I'll reopen the issue and look into it more.
