### ISSUE TITLE
Effect Packet Errors caused by JustEnoughIDs

### ISSUE THREAD

**Issue by knoxhack** [DimensionalDevelopment/JustEnoughIDs#41]
Bug Report:
With the latest release of the pack (1.0.21) we have encountered packet errors caused by JustEnoughIds recent extended enchantment and potion packet ID changes.

This error occurs both while connecting and after connection resulting in the user being kicked, it's especially aggravated by network proxies such as WaterFall or Velocity.

At the moment the only solution to this would be to downgrade JustEnoughIDs on both the client and server.

Steps to Reproduce (for bugs)
Connect to a server, networked servers using a proxy such as WaterFall or Velocity causes this to happen more frequently.
Be disconnected by a packet error either on connect, during game-play or while switching servers.
Logs
Client/Server Log: https://gist.github.com/PurpleIsEverything/3e656340a112249f67250ec771c9e48e
Client Information
Modpack Version: Stoneblock 1.0.21
Server/LAN/Single Player: Server
Optifine Installed: No
Shaders Enabled: No

**Comment by knoxhack** [comment]
For more info: 
https://github.com/Sunekaer/stoneBlock/issues/370

**Comment by ZombieHDGaming** [comment]
I left a response on that ticket, but I'll still put it here:
```
I'll be honest, there's not much I can do personally about this as it's not actually an issue with JEID, it's more on Waterfall/Velocity/BungeeCord/whoever and how they handle the packets. If it's honestly not needed, I'd roll back to the previous build of JEID you used without the potion and enchantment extensions (JustEnoughIDs 1.0.2-16) to prevent issues with people who use proxy servers for server networks, because besides the extensions, the builds are practically the same. But yeah, sorry I couldn't be of much help besides that.
```

**Comment by PurpleIsEverything** [comment]
I also left a response, but for reference I'll put it here too.

```We investigated it further and in the case of Velocity or Waterfall with alt-respawn modifications neither handles these packets nor rewrites entity IDs.

The most they do that seems to aggravate this is resend the login packet and reset the FML handshake when switching servers. Login packets are vanilla and it's the right way to handle things.

So to be clear, it's easier to replicate with a proxy but still occurs without one.```
