### ISSUE TITLE
Causes Biomes O' Plenty to crash

### ISSUE THREAD

**Issue by 189236** [DimensionalDevelopment/JustEnoughIDs#43]
https://paste.dimdev.org/hevukahigo.mccrash
See Glitchfiend/BiomesOPlenty#1332

**Comment by ZombieHDGaming** [comment]
Not even using JEID.

**Comment by Diamondman121314** [comment]
You're not even using the latest version of NotEnoughIDs anyway. Update that first and if you have any other problems, report that to the NotEnoughIDs GitHub Issues.
