### ISSUE TITLE
Just Enough Dimension Biome

### ISSUE THREAD

**Issue by Vyraal1** [DimensionalDevelopment/JustEnoughIDs#47]
![image](https://user-images.githubusercontent.com/26587049/49343904-6bb17f80-f63e-11e8-869b-cd2cabb3b8c2.png)

Was using [TellMe](https://minecraft.curseforge.com/projects/tellme) to do a biome dump and saw the following, I'm just reporting it as you requested.

**Comment by ZombieHDGaming** [comment]
That's the actual biome registered, not an errored biome. Just ignore.
