### ISSUE TITLE
Creeping Nether 2.2  crash

### ISSUE THREAD

**Issue by Dread-chan** [DimensionalDevelopment/JustEnoughIDs#48]
I've been getting some crash reports on my mod [The Creeping Nether](https://minecraft.curseforge.com/projects/the-creeping-nether).
https://paste.dimdev.org/rejivepedu.mccrash
https://pastebin.com/raw/DXAMTjdt
We've identified that the incompatability is with JEID.
I understand you've added a [mixin](https://github.com/DimensionalDevelopment/JustEnoughIDs/blob/master/src/main/java/org/dimdev/jeid/mixin/modsupport/MixinEntityPortal.java) to support the biome corruption in my mod, but in the newest version of my mod I've moved the biome corruption logic from EntityPortal to CorruptorAbstract and this seems to be causing problems. I don't know how to fix this on my own, so I'm hoping you can help.

**Comment by Sunconure11** [comment]
@Runemoro

**Comment by coldReactive** [comment]
I'm the one who did this pastebin: https://pastebin.com/raw/DXAMTjdt

Posting here to keep thread alive and adding to participants.

**Comment by ZombieHDGaming** [comment]
Should be fixed in latest commits, but proper testing might need to be done.

**Comment by sk2048** [comment]
You have not made all the changes necessary to your mixin. There is not a field named `toBiome` on AbstractCorruptor. Instead you should be shadowing `public abstract Biome getBiome()`, and calling that whenever you need to know the target biome.
