### ISSUE TITLE
"A mod doesn't support extended biome ID's, report to Just Enough ID's

### ISSUE THREAD

**Issue by valoeghese** [DimensionalDevelopment/JustEnoughIDs#49]
Biomes Mods Used: Biomes you go, Traverse, NetherEx, Project: Vibrant Journeys, Zoesteria Biomes

**Comment by Runemoro** [comment]
Where do you see the message?

**Comment by valoeghese** [comment]
I believe it's listed as a biome in Nature's Compass (another mod I'm using)

**Comment by ZombieHDGaming** [comment]
Duplicate of #45 potentially
