### ISSUE TITLE
Custom biome support needed for some mods

### ISSUE THREAD

**Issue by Sunconure11** [DimensionalDevelopment/JustEnoughIDs#5]
Not sure what, but I compiled a list of mods I am using + various other biome-adding mods. Note that I am not using all of these mods, I am just listing them.

I've got a list of mods with their own biomes i'd like you to go through and see if any fixes are needed. One also lets you locate biomes

- [x] nature's compass
- [x] twilight forest - PacketBiomeChange
- [x] erebus
- [x] the betweenlands
- [x] aether ii
- [x] aether legacy
- [x] thaumcraft - PacketBiomeChange
- [x] biomes o' plenty
- [x] traverse
- [x] terra
- [x] sugi forest
- [x] abyssalcraft - CleansingRitualMessage
- [x] defiled lands
- [x] misty world
- [x] floricraft
- [x] creeping nether - EntityProtal.corruptBiome
- [x] ice and fire
- [x] biosphere expansion
- [x] real world
- [x] the forgotten biomes
- [x] spooky biomes
- [x] netherex
- [x] justenoughresources
- [x] streams
- [x] aroma's dimensions
- [x] dimensionalcontrol
- [ ] ~~~void island - IslandRegistry~~~
- [x] bedrockbegone
- [x] Weather, Storms & Tornadoes
- [x] ClimateControl - DimensionManager.hasOnlySea
- [x] SkyLandsForge
- [x] openterraingenerator
- [x] biomebundle
- [x] rftools dimensions
- [x] welcome to the jungle
- [x] dynamic trees
- [x] biometweakercore
- [x] growthcraft
- [x] buildcraft
- [x] galacticraft
- [x] dimensional doors
- [x] mystcraft - SymbolFloatingIsland.BiomeReplacer
- [x] tough as nails
- [x] serene seasons
- [x] dynamic surroundings
- [x] fossils and archaeology
- [x] tropicraft
- [x] streams
- [x] dumpster diving
- [ ] ~~~open cubic chunks~~~
- [x] advanced rocketry

https://minecraft.curseforge.com/mc-mods/world-gen/world-biomes?filter-game-version=2020709689:6756&filter-sort=4
https://minecraft.curseforge.com/mc-mods/world-gen/world-dimensions?filter-game-version=2020709689%3A6756&filter-sort=4
https://minecraft.curseforge.com/mc-mods/world-gen?filter-game-version=2020709689%3A6756&filter-sort=4

**Comment by Sunconure11** [comment]
While testing against Terra, I found this issue with BoP, when teleporting to a green beach.

https://paste.dimdev.org/arowuyesut.mccrash

**Comment by Runemoro** [comment]
Twilight Forest, Thaumcraft, Abyssialcraft, and Creeping Nether will all need support for biome update packets. What this means is that their worldgen will work correctly, but biome changing tools/spells/features will not resync the client until leaving and re-entering the world. So grass/leaves/sky colors might not update, but other than that, everything should work properly. I will be adding support for those in the next few days.

I'm not sure why the crash with BoP happened, but I saw it while testing in dev with just BoP a while ago, and haven't been able to reproduce it. I'll ask in the BoP discord to see if they might know what's wrong.

**Comment by Runemoro** [comment]
Lost Cities isn't supported, see #4

**Comment by Sunconure11** [comment]
Encountered the same BoP crash without JEID.

https://pastebin.com/AHBKExq1

**Comment by Sunconure11** [comment]
When I managed to locate a wasteland, the biome completely changed into a tundra. WTF?

**Comment by Sunconure11** [comment]
https://github.com/Glitchfiend/BiomesOPlenty/issues/1284

**Comment by jredfox** [comment]
again why hard coded support just make a dynamic biome system that has extended ids this isn't acceptable to have hard coded support meaning any new or mods not in the hard coded list will glitch out the mod

**Comment by Sunconure11** [comment]
For safe measure, test against Terra Novam.

**Comment by Runemoro** [comment]
No, biomes don't have integer IDs or resource locations. Adding support for other mods is easier and faster than getting them to support int biome IDs (and would also require them to add JEID as a dependency).

**Comment by jredfox** [comment]
well there needs to be some sort of established interface to communicate between the biome id and biome. 

so is every biome incompatible? if so I would say biomes cannot be extended without using your api at all and ids should start above the max value. Also I would make a forge pull request for extending something like this that breaks other mods
