### ISSUE TITLE
Ticking Entity Crashes on BoP world generation

### ISSUE THREAD

**Issue by Salamance73** [DimensionalDevelopment/JustEnoughIDs#55]
I have about 170 mods loaded atm, everything was generating fine with my old worldgen mod (biome bundle) but I decided to switch to BoP, added jeid, as neid was making the same crash. It doesn't seem to have a set block that it does it on, just random entities/blocks. Any help would be great, thanks.
https://paste.dimdev.org/esiwaromal.mccrash
https://paste.dimdev.org/xanuyegahe.mccrash

**Comment by ZombieHDGaming** [comment]
Yeah, definitely an OTG issue. There's no mention of us and it seems to be missing a class.

**Comment by Salamance73** [comment]
Sorry about that, forgot to delete the remaining OTG files since BoP doesn't need them, thanks.
