### ISSUE TITLE
can't change biomes 

### ISSUE THREAD

**Issue by Varg95** [DimensionalDevelopment/JustEnoughIDs#57]
i use evilcraft or Extra Utilities 2 to change biomes to other biomes. Before i added JustEnoughIDs it worked fine but now it doesnt work at all. 

I use Forge Mod Loader version 14.23.5.2796, JustEnoughIDs-1.0.2-26, EvilCraft-1.12.2-0.10.56

Thanks for your time i hope it can be fixed soon.

**Comment by ZombieHDGaming** [comment]
Fixed in latest commits.
