### ISSUE TITLE
The Betweenlands doesn't work with extended biome ID's.

### ISSUE THREAD

**Issue by viceroy369** [DimensionalDevelopment/JustEnoughIDs#59]
I try to add the Betweenlands to my world with well over 256 biomes only to be greeted by this:

https://ibb.co/5WL0JxR

The problem is definitely the extended biome id's, because when I remove a few overworld biome mods the dimension works just fine.

**Comment by viceroy369** [comment]
Fixed by this mod - [Just Enough ID's Integrations]https://minecraft.curseforge.com/projects/justenoughids-integration-jeidsi.

**Comment by ZombieHDGaming** [comment]
Fixed in latest commits.
