### ISSUE TITLE
Expand potion and enchantment IDs

### ISSUE THREAD

**Issue by Sunconure11** [DimensionalDevelopment/JustEnoughIDs#6]
Unless those were taken care of, I don't see any code relating to them.

**Comment by PulseBeat02** [comment]
I also would like this enchancement.

**Comment by Runemoro** [comment]
That's not a problem. JEID will modify the packet to send it as an int. JEID already does the same for chunk update packets since vanilla Minecraft sends biome IDs as bytes too.

**Comment by Sunconure11** [comment]
Wait, I remember discussing packets regarding a different mod in the past. Is it possible to extend the type of packet it is calling for in this error?

https://user-images.githubusercontent.com/5614902/42818207-3cc93d1e-899e-11e8-9f13-0f9fa3a14d6b.png

The mod causing this one in question is Howling Moon. I was never able to find the cause, and sort of gave up.

**Comment by Hypsellis** [comment]
It would be awesome if all the new code features and fixes of 1.13 could be included in JEID and VanillaFix.

**Comment by ZombieHDGaming** [comment]
Fucking finally done. Both will be released in the next release which is being reviewed atm.
