### ISSUE TITLE
A mod doesn't support extended biome IDs -- report to JEID

### ISSUE THREAD

**Issue by aevumdefluo** [DimensionalDevelopment/JustEnoughIDs#65]
Not sure what to do except report it here. Mods I am currently using:

![mods](https://user-images.githubusercontent.com/18394420/57726890-2322d700-765e-11e9-82ba-afa83268526e.png)

**Comment by Runemoro** [comment]
Where do you see this message?

**Comment by aevumdefluo** [comment]
Ah! Sorry. I forgot to post it as I had no sleep yesterday. It was in a file that was output from the mod tellme. I was checking the biome ids.
[biomes-id-to-name_2019-05-14_15.11.06.txt](https://github.com/DimensionalDevelopment/JustEnoughIDs/files/3183616/biomes-id-to-name_2019-05-14_15.11.06.txt)

**Comment by Runemoro** [comment]
Not an issue then. It's listing all biomes, including the JEID error biome which is meant to show up when a mod uses the old biome array.

**Comment by CritFlaw** [comment]
This happens in every biome I try the staff in.

**Comment by CritFlaw** [comment]
Apparently this mod is undocumented, and that's why mods can't integrate with it. Consider documenting the code?

**Comment by Runemoro** [comment]
> Apparently this mod is undocumented, and that's why mods can't integrate with it. Consider documenting the code?

Mods don't need to integrate with JEID. They only need to not assume that biome ids fit inside bytes.

As I already said on the other issue, you should ignore this message. It's a fake message caused by the fact that a mod is listing every biome.
