### ISSUE TITLE
jeids crash with vanillafix

### ISSUE THREAD

**Issue by Mrthomas20121** [DimensionalDevelopment/JustEnoughIDs#69]
[latest.log](https://github.com/DimensionalDevelopment/JustEnoughIDs/files/3305224/latest.log)
when i install jeids in the pack im working on it crash and won't let me load it.
any idea what is causing this?

also i see sponge stuff in there where there shouldn't be any since im not running sponge

jeids version: JustEnoughIDs-1.0.2-26
vanillafix version: 1.0.10-99

**Comment by Mrthomas20121** [comment]
just tried using the latest version of vanillafix and still get the crash

**Comment by WeirdDude96** [comment]
include the crash report - i think I might be getting the same crash

**Comment by Mysticpasta1** [comment]
fixed in latest of both mods it seems
