### ISSUE TITLE
java.lang.NoClassDefFoundError: net/minecraft/world/gen/ChunkProviderServer with SpongeForge 3847

### ISSUE THREAD

**Issue by LemADEC** [DimensionalDevelopment/JustEnoughIDs#73]
As of 1.0.2-26, game will crash when loading the world with Spongeforge-1.12.2-2838-7.1.7-RC3847 + forge-14.23.5.2838.
https://gist.github.com/LemADEC/83974e7bcb34ca02f9ead3335c435cf9

Issue isn't reproduced with spongeforge-1.12.2-2838-7.1.7-RC3785.

**Comment by lampyr** [comment]
hello i have the same problem.

**Comment by BlazeRuler** [comment]
I am too
The people at SpongeForge are saying it's this mod doing it.

**Comment by sk2048** [comment]
It is not right to pin the blame on this mod. SpongeCommon has introduced new and substantial changes to `ChunkProviderServer` - a core component of Minecraft, also modified by this mod. These could not possibly have been anticipated when this mod was written and are incompatible with the current set of changes made by this mod.

Understand that this should not be considered a bug report, but a feature request. This requires at least one new core mixin to be written for use only when Sponge is running, and will require not insignificant time to develop and test.

**Comment by Zidane** [comment]
I agree, we'll debug this more on our end. Your change to ChunkProviderServer isn't significant.

**Comment by Zidane** [comment]
I said I'd look into this and so I did:

https://github.com/DimensionalDevelopment/JustEnoughIDs/pull/79

**Comment by Runemoro** [comment]
@Zidane fixed this, I'll make a new CurseForge version in a few hours!

**Comment by xJon** [comment]
Is there any update?

**Comment by LemADEC** [comment]
Already fixed and published. Still working fine with justenoughdimensions-1.12.2-1.6.0-dev.20190711.220109.
