### ISSUE TITLE
CreepingNether Compat

### ISSUE THREAD

**Issue by Duvetyn** [DimensionalDevelopment/JustEnoughIDs#74]
Will you add compatibility with Creeping Nether please? Trying to use both mods at once causes a crash and a crash report ranting about a 'cutievirus.'

Here's a link to Creeping Nether
https://www.curseforge.com/minecraft/mc-mods/the-creeping-nether

**Comment by sk2048** [comment]
Until support is fixed here, I’ve written a mod to help with this and other issues that arise from using JEID with other mods. This includes The Creeping Nether.

https://www.curseforge.com/minecraft/mc-mods/justenoughids-integration-jeidsi
