### ISSUE TITLE
Environs++ biomes doesn't support extended Biome IDs

### ISSUE THREAD

**Issue by Fireztonez** [DimensionalDevelopment/JustEnoughIDs#75]
Hello,
When I look on Journey Map's Fullscreen maps, biomes from Environs++ show the message `a mod doesn't support extended biome IDs`. I look and you say on your curse page to open an issue about that, so, here it is!!

Strange Enough, the biome name is shown in the mini-map, but doesn't show on the full-screen map, but I imagine this is just because Journey map look for biome name using 2 different methode... When I look with F3 it say Biome: Canyon... So not sure if the issue is from JEID or if the issue is with Journey Maps... It can be incompatibility with both Journey Maps, and Environs++  and JEID... I think you probably know more than me ;-) ...

Versions:
JustEnoughIDs 1.0.2-26
JustEnoughIDs Integration: 1.3.1.42
JourneyMaps-1.12.2-5.5.5b9
Environs++ 1.12.2-1.1 pre1 (BETA)
Forge: 14.23.5.2838

Thank's

**Comment by viceroy369** [comment]
This is a problem with Journeymap not Environs++. You need JEID integrations mod.

**Comment by Runemoro** [comment]
See https://github.com/DimensionalDevelopment/JustEnoughIDs/issues/158.
