### ISSUE TITLE
Problem with updating my world to newer versions

### ISSUE THREAD

**Issue by WarriorsCode1** [DimensionalDevelopment/JustEnoughIDs#77]
If I use JEID to create my world in 1.12.2 and then update Minecraft to 1.13 or 1.14 it will corrupt my whole world. I know that -  "Extremely important: Removing JustEnoughIDs will break your world. It is equivalent to loading a 1.13 world in 1.12!" - but is it possible to use the world in a newer version 
again?

**Comment by Runemoro** [comment]
No, it's not compatible with 1.13. Almost all mods broke compatibility with 1.13 anyway, so there's no point in writing an updater since it's almost impossible the world will work even if it was updated.
