### ISSUE TITLE
Quantum Quarry Biome marker Does not work 

### ISSUE THREAD

**Issue by AsimRamay** [DimensionalDevelopment/JustEnoughIDs#78]
so i spent a few hours working out that QQ biome markers dont work with QuantumQuarry , i disabled mods one by 1 , then when disabling JEID worked , i tried just Extra Utilities 2 With JEID enabled and the biome once set will not change (kinda weird as to get the biome ID u need to use the biome marker in the zone you are in, so i would assume it would copy it from the chunk information )
using:
extrautils2-1.12-1.9.9
JustEnoughIDs-1.0.2-26

Update: 
seems to be that after it generates the chunk using the Biome Marker it cant save the chunk - and that's the problem  but it can regenerate the initial chunk over and over (quarry works perfectly otherwise, except for changing biome) 
[Server thread/ERROR] [minecraft/AnvilChunkLoader]: Failed to save chunk

**Comment by sk2048** [comment]
This should be fixed by including JustEnoughIDs Integration v1.3.2.45+, which is available on Curseforge.

For future reference: robertdroptables-mcmods/JEIDsIntegration@14fc99c7c474711db7408b41f0e5abb3f47a53cb

**Comment by AsimRamay** [comment]
Ah thanks for the heads up ,  ill try it now - thats a  good reminder to check dependent as well as dependency relations - thank you so much
