### ISSUE TITLE
bug causing crash with Twilight forest

### ISSUE THREAD

**Issue by ValentineBlaze** [DimensionalDevelopment/JustEnoughIDs#80]
so this is causing a crash on startup https://paste.dimdev.org/egasilovox.mccrash and i am sure someones brought it to your attention already but just incase they haven't I would love for a fix of some form. the twilight team says its a problem with yall and not them
Edit: you already had a fix with the jeid intergration ignore me

**Comment by Phorcis** [comment]
Same problem

**Comment by Phorcis** [comment]
where i can find jeid intergration?

**Comment by Phorcis** [comment]
> so this is causing a crash on startup https://paste.dimdev.org/egasilovox.mccrash and i am sure someones brought it to your attention already but just incase they haven't I would love for a fix of some form. the twilight team says its a problem with yall and not them
> Edit: you already had a fix with the jeid intergration ignore me

where are i can find jeid intergration?
