### ISSUE TITLE
Biometweaker Compat

### ISSUE THREAD

**Issue by mxnmnm** [DimensionalDevelopment/JustEnoughIDs#84]
I created too many biomes using biometweaker so I had to install just enough ids to increase the biome id limit but when I did that the biome dump in biometweaker gave me an error that said just enough ids was at fault.  Here's what the error's name was "A_mod_doesn_t_support_extended_biome_IDs_--_report_to_JEID (jeid_error_biome)" if you want more info let me know.

**Comment by ZombieHDGaming** [comment]
1. That's most likely just for JEID's debug biome that is registered anyway, and 2. Compat is already included in the most recent commits and will be in the next release, which might be out within the next couple days.
