### ISSUE TITLE
Very early crash

### ISSUE THREAD

**Issue by Shattered2909** [DimensionalDevelopment/JustEnoughIDs#87]
Heya, working on a modpack right now, got this crash:
https://paste.dimdev.org/taweyorene.mccrash

Asked some friends cuz im not very experienced and they think your mod is causing this, maybe needs fixing, maybe im being an idiot. If you want more log, please ask!

**Comment by ZombieHDGaming** [comment]
Remove JustEnoughIDsIntegration, it's literally in in all caps, bolded and red in the change log for 1.0.3

**Comment by Shattered2909** [comment]
okay, thanks!
