### ISSUE TITLE
Broken Worldgen

### ISSUE THREAD

**Issue by mxnmnm** [DimensionalDevelopment/JustEnoughIDs#89]
Mod List-https://pastebin.com/msdFc8rN
JustEnoughIDs 1.0.3-44

So I updated Just Enough IDs and everything was fine until i started to go out a bit further and explore stuff I was messing around with and boom it's all void.  The first thing I did was load a new world to see if it still happens and it did.  This only happens with the latest version and it works normally with everything before that.

here's a screenshot of the world with the new version loaded and the old version loaded-https://imgur.com/a/344HsJm

If you need anymore info let me know

**Comment by Malderest** [comment]
I suggest removing NotEnoughIDs from that mod list as that resolved the very same problem during my testing.

**Comment by mxnmnm** [comment]
Oh I didn't even realize that was installed lololol I must've installed it at some point and forgot about it existing lol

**Comment by mxnmnm** [comment]
Yea I'll test right now to double check if it works and if it does I'll close this issue

**Comment by mxnmnm** [comment]
Yep that was the issue ty

**Comment by ErnestoPeroPezzi** [comment]
I am also having this issue, but Im too far gone to just remove NEIDs. I have both neids and jeids loaded, they used to work just fine, but for osme reason, world has stopped generating like OP has said.

Apologies for doing this on a closed issue but I am at my wits end with this. Is there a way to fix?

**Comment by RebornSplash60official** [comment]
Will this be fixed in a future update?
