### ISSUE TITLE
Crash during starting minecraft

### ISSUE THREAD

**Issue by tmvkrpxl0** [DimensionalDevelopment/JustEnoughIDs#90]
I use JustEnoughIDs lastest version(1.0.3) on 1.12.2
Here is the crash report: https://del.dog/ironixizeb.rb

**Comment by sk2048** [comment]
You still have JEIDsI installed. Remove it as it is no longer necessary. All fixes are merged into JEID.

**Comment by tmvkrpxl0** [comment]
thanks
