### ISSUE TITLE
Crash with JustEnoughIDs 1.0.3-44

### ISSUE THREAD

**Issue by MokahTGS** [DimensionalDevelopment/JustEnoughIDs#91]
Getting a crash with JEIDs latest version:

MC 1.12.2
Forge 2838
JustEnoughIDs 1.0.3-44

Crash Log: https://paste.dimdev.org/wiganifuwa.mccrash

Full Mod List: https://paste.dimdev.org/qedajudexo.md

Rolling back a version fixes it.

**Comment by ZombieHDGaming** [comment]
*Bangs head against wall for the thousandth time* You have to remove JEIDsI, it's been merged into the mod. I made it red and bold in large text for a reason 😭
