### ISSUE TITLE
[1.12.2] Crash after Update

### ISSUE THREAD

**Issue by Caaruzo** [DimensionalDevelopment/JustEnoughIDs#92]
Hello :)

Today i tryed to update the JEIIDS mod in a personal modpack.
After done, Minecraft wont start anymore and crashes. With the previous Version (JustEnoughIDs-1.0.2-26) it worked well.

Hope you can fix that.

**Minecraft Version:** 1.12.2
**Forge Version:** forge-1.12.2-14.23.5.2838-universal
**JEIID Version:** JustEnoughIDs-1.0.3-44

**Logs Below**

[crash-2019-09-03_21.40.32-client.txt](https://github.com/DimensionalDevelopment/JustEnoughIDs/files/3571179/crash-2019-09-03_21.40.32-client.txt)
[latest.log](https://github.com/DimensionalDevelopment/JustEnoughIDs/files/3571200/latest.log)

**Comment by ZombieHDGaming** [comment]
Always read the update log before updating any mod. There's a note I left in red, bold, large text saying to remove JEIDsI from your mods as it has been merged into JEID.

**Comment by Caaruzo** [comment]
oh ok didnt seen that iam really sorry 👍
