### ISSUE TITLE
Dedicated Server Issue w/ Advanced Rocketry (JEIDs 1.0.3)

### ISSUE THREAD

**Issue by nephatrine** [DimensionalDevelopment/JustEnoughIDs#93]
JEIDs 1.0.3-44 does not appear to function with Advanced Rocketry on a dedicated server (tried both latest 1.12.2-1.6.0-180 as well as 1.12.2-1.6.0-164). It does seem to work on a client.

Pastebin:
https://pastebin.com/TbbvkfAG

If I switch to JEIDs 1.0.2 and add JEIDsI, it does not seem to be an issue and I can start a server. So it seems when the compat was moved from jeidsi to the main mod something broke.

I had opened a separate issue on the Advanced Rocketry page before they pinpointed that the issue was with JEIDs.

https://github.com/zmaster587/AdvancedRocketry/issues/1692

**Comment by vacla** [comment]
with the latest version of JEID, you don't need JEIDsl anymore

**Comment by sk2048** [comment]
@ZombieHDGaming either split the mixin in two and apply the executeClient section only on the client, or restore the line linked below removed for no reason and clearly untested.

https://github.com/robertdroptables-mcmods/JEIDsIntegration/blob/master/src/main/java/uk/bobbytables/jeidsi/core/compat/advancedrocketry/mixins/MixinPacketBiomeIDChange.java#L76
