### ISSUE TITLE
Class Not Found Exception 1.0.3-44 crashing server on startup

### ISSUE THREAD

**Issue by kreezxil** [DimensionalDevelopment/JustEnoughIDs#94]
Issue:  1.0.3-44 crashes dedicated server Forge 1.12.2 build 2847

Notes:

crash report:
http://paste.ubuntu.com/p/JXMP8gkQGn/

fml server latest:
http://paste.ubuntu.com/p/tG7DhptMvN/

**Comment by sk2048** [comment]
Remove JEIDsI.
