### ISSUE TITLE
"A mod doesn't support extended biome IDs" shows up in mods that list biomes

### ISSUE THREAD

**Issue by katubug** [DimensionalDevelopment/JustEnoughIDs#97]
Hi! I'm not sure if there's an erroring biome in my pack, or if Nature's Compass is trying to load an incorrect biome added by JEID? But here is what I see when I look at the Nature's Compass GUI:

![2019-09-28_20 01 58](https://user-images.githubusercontent.com/20935286/65824217-d74a8600-e22a-11e9-9c76-cf79243dcaa0.png)

I have tried to blacklist the error biome from appearing in the list via the Nature's Compass config, but it doesn't seem to have worked.

* **Minecraft version:** 1.12.2
* **Forge version:** forge-1.12.2-14.23.5.2838-universal
* **Modpack version** (links to current modlist): [1.7.2](http://enthusiasticraft.cf/modpack-update-1-7-2/#modlist)
* **Mod versions:** JustEnoughIDs-1.0.3-44, NaturesCompass-1.12.2-1.5.1

Please let me know if I should provide any other information. :) Thank you for your time!

**Comment by sam-kirby** [comment]
There's no issue here, listing all biomes necessarily includes the JEID error biome. Here is an example of it being blacklisted successfully:

https://github.com/DarkPacks/SevTech-Ages/blob/master/src/config/naturescompass.cfg#L18

**Comment by katubug** [comment]
Ah, that helps immensely. I had tried disabling it via numeric id, which failed. I'll try the method they used. Thank you! :) I appreciate it.

**Comment by Runemoro** [comment]
The error biome will be removed to fix this and many other issues.

It was originally intended to make incompatibilities obvious by showing up when a mod uses the old byte biome array to get a biome, but it also shows up every time a mod lists all biomes. Almost a quarter of JEID issues are related to this (incorrect) message showing up in some biome list.

**Comment by katubug** [comment]
That makes sense, both the explanation and the solution. Sorry for the trouble, and thank you for helping!

**Comment by Runemoro** [comment]
See https://github.com/DimensionalDevelopment/JustEnoughIDs/issues/158.
